#!/usr/bin/python
import os
import subprocess

if __name__ == '__main__':
    load = subprocess.check_output("nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader", shell=True)
    load = load.decode()[:-1]
    load = load.replace(" ", "")

    # parse options
    l_warn = 70
    if 'L_WARN' in os.environ.keys():
        l_warn = float(os.environ['L_WARN'])
    l_crit = 90
    if 'L_CRIT' in os.environ.keys():
        l_crit = float(os.environ['L_CRIT'])
    if 'WARN_COLOR' not in os.environ.keys():
        os.environ['WARN_COLOR'] = "#FFFC00"
    if 'CRIT_COLOR' not in os.environ.keys():
        os.environ['CRIT_COLOR'] = "#FF0000"

    warn = False
    crit = False
    if float(load[:-1]) > l_crit:
        crit = True
    elif float(load[:-1]) > l_warn:
        warn = True

    os.system("echo " + load)
    os.system("echo " + load)
    if warn:
        os.system('echo "' + os.environ['WARN_COLOR'] + '"')
    elif crit:
        os.system('echo "' + os.environ['CRIT_COLOR'] + '"')

