#!/usr/bin/env sh

WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

	# the position of the upper left corner of the popup
	#posX=$(($BLOCK_X - $WIDTH / 2))
	#posY=$(($BLOCK_Y - $HEIGHT))

  if [[ "$DESKTOP_SESSION" == "i3"  ||  "$DESKTOP_SESSION" == "/usr/share/xsessions/i3" ]]; then
    i3-msg 'exec --no-startup-id gnome-calendar' > /dev/null
    i3-msg \[app_id='gnome-calendar'\] move container to workspace current, focus > /dev/null
	elif [[ "$DESKTOP_SESSION" == "sway"  ||  "$DESKTOP_SESSION" == "/usr/share/wayland-sessions/sway" ]]; then
    swaymsg 'exec --no-startup-id gnome-calendar' > /dev/null
    swaymsg \[app_id='gnome-calendar'\] move container to workspace current, focus > /dev/null
  fi
  #i3-msg 'exec --no-startup-id "kitty --title calcurse-dropdown ikhal"' > /dev/null
esac
echo "$LABEL$(date "$DATEFMT")"
echo "$LABEL$(date "$SHORTFMT")"
